### ISSUE TITLE
Dataview link() function not filtered out

### ISSUE THREAD

**Issue by Narwhai** [Quorafind/Bases-Toolbox#1]
This Dataview Query:

```
table  
	director as Director,
	status as Status,
	startDate as Release
from #anime
where contains(director, link("Goro Miyazaki"))
sort startDate desc
```

Give this output:

```
views:
  - type: table
    name: Default view
    order:
      - director
      - status
      - startDate
    filters:
      and:
        - taggedWith(file.file, "anime")
        - contains(director, link("Goro Miyazaki"))
    sort:
      - column: startDate
        direction: DESC
display:
  director: Director
  status: Status
  startDate: Release
```

In the filters section, `link("Goro Miyazaki")` is not a valid Bases function, changing it to `contains(director, "[[Goro Miyazaki]]")`  or `contains(director, "Goro Miyazaki")` would be preferred. 

Additionally, wondering if a plain TABLE query should also include `name` as a column in the Base. 

TABLE WITHOUT ID should omit it, by TABLE includes a link to the note by default
