### ISSUE TITLE
Syntax error at column 28 of formula. Unexpected ident token: "I".

### ISSUE THREAD

**Issue by taurean** [Quorafind/Bases-Toolbox#4]
Hi! I'm attempting to convert the following dataview query but I'm receiving this error. One or more elements of this query might not be supported so this could totally be my fault but I'm not sure so I'm submitting a bug just in case.

the data view input:

```SQL
TABLE without id
	issueNumber as "Issue Number",
	link(file.link, string(publishDate)) as "Published on",
	choice(round(rating) = null, "",
	    choice(rating <= 1, "★☆☆☆☆",
			choice(rating = 2, "★★☆☆☆",
                choice(rating = 3, "★★★☆☆",
                    choice(rating = 4, "★★★★☆",
                        choice(rating <= 5, "★★★★★", "")
                    )
                )
			)
		)
	) as "Rating"
WHERE
	contains(entityIs, [[Comic Issues Collection|Comic Issues]]) AND contains(series, this.file.link) AND !contains(file.folder, "curtain")
SORT issueNumber asc
```

and the output:

```YAML
views:
  - type: table
    name: Default view
    order:
      - issueNumber
      - formula.published_on
      - formula.rating
    sort:
      - column: issueNumber
        direction: ASC
display:
  issueNumber: Issue Number
  formula.published_on: Published on
  formula.rating: Rating
formulas:
  published_on: link(file.link, string(publishDate))
  rating: >-
    choice(round(rating) == null, "", choice(rating <= 1, "★☆☆☆☆", choice(rating
    == 2, "★★☆☆☆", choice(rating == 3, "★★★☆☆", choice(rating == 4, "★★★★☆",
    choice(rating <= 5, "★★★★★", ""))))))
filters:
  and:
    - contains(entityIs, [[Comic Issues Collection|Comic Issues]])
    - contains(series, this.file.link)
    - not(contains(file.folder, "curtain"))
```

the error produced: 

```markdown
Unable to parse your base file:

Syntax error at column 28 of formula. Unexpected ident token: "I".
```

currently the data view renders like this:

<img width="690" alt="Image" src="https://github.com/user-attachments/assets/9764341e-8f50-4de5-b13d-d57c4bd777b0" />
